# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d6948bb8585dcbaa15ae1a5ef13964dcd1ea97935801212eee2934675607d756559b9a7e2ca39ca98cec23d66e4e8cf2c48acd7a6d683e83839ad9fc581b95

test:
  secret_key_base: dbda188a65b87796a96e2acd8f12fffdc046be76e73b144d52c20b7b0b4f9e3f0d6ed2a83e7b50ffbdc922792aa1930af5793776e59faa3f11cfb9cf89954ee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
